title: elchris414's blog
email: me@chrisch.dev
description: >-
  Just a blog of the different things that I elchris414 want to say
baseurl: ""
url: "https://chrisch.dev"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate

paginate: 1
paginate_path: "/p:num/"

permalink: "/:year/:month/:day/:title/"

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      is_post: true

exclude:
  - README.md
  - _archive/
